name: Code analysis & unit tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  # Runs all steps on the VM
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x, 20.x, 22.x]

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --recursive --frozen-lockfile

      - run: pnpm check
