name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  # Runs all steps on the VM
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [16.x, 20.x, 22.x]

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - run: pnpm i --frozen-lockfile
      - run: pnpm test
